CREATE DATABASE  IF NOT EXISTS `personajes`;
USE `personajes`;

DROP TABLE IF EXISTS `characters`;
CREATE TABLE `characters` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_date` datetime(6) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `role` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4;


LOCK TABLES `characters` WRITE;
INSERT INTO `characters` VALUES (1,'2025-03-14 15:18:24.000000','Walter \"Walt\" Hartwell White, también conocido por su seudónimo clandestino \"Heisenberg\", es un químico y profesor de química de Albuquerque,( Nuevo México) que, tras ser diagnosticado con cáncer de pulmón inoperable, decide empezar a fabricar metanfetamina para poder mantener a su familia provista de cara al futuro.\nWalt era un químico prometedor que contribuyó en el auge de la compañía multimillonaria Gray Matter Technologies, pero salió de la empresa de forma abrupta vendiendo su parte de la misma por cinco mil dólares. Los fundadores Elliott y Gretchen Schwartz se casan y hacen una fortuna, mientras que Walt les acusa de apoderarse de sus contribuciones para tener éxito sin darle ningún crédito.','/api/files/1e48366f-cdf8-444e-bad5-5ce4083476c8_Walter.jpeg','Walter White','Químico de Sandia National Laboratories'),
(2,'2025-03-14 15:21:43.000000','Jesse Bruce Pinkman es el compañero de Walter White en el tráfico de metanfetamina. En el instituto, Jesse era un consumidor, fabricante y traficante de poca monta de metanfetamina. Era un estudiante que prestaba poca atención a las clases de química de su profesor, el propio Walter. Años después, Jesse se dedica al tráfico de droga con el seudónimo \"Cap\'n Cook\" y añade polvo de chili a su producto para caracterizarlo.\nAl buscar a Jesse para que trabajen juntos, Walter insiste en hacer un producto más puro, dejando de utilizar la pólvora de chili y enseñando a Jesse a cocinar un mejor producto. A menudo trata a Jesse como un hijo problemático que a menudo necesita que le corrijan. A pesar de la fricción entre ambos, él y Walt tienen una profunda lealtad el uno hacia el otro. La propia familia de Jesse le echó de casa por sus problemas con las drogas.','/api/files/fd9699fe-0fe4-4c05-8517-0d2f1ae610b9_Jesse.jpeg','Jesse Pinkman',' Proveedor y traficante de metanfetamina'),
(3,'2025-03-14 15:23:20.000000','Gustavo \"Gus\" Fring era el líder criminal de un imperio de drogas y el dueño de la cadena de restaurantes Los Pollos Hermanos. Un magnate de negocios y filántropo nacido en Chile. Inicialmente estaba afiliado al Cártel de Juárez, que utilizaba en secreto sus restaurantes como una tapadera legítima para la distribución de metanfetamina en todo el suroeste de Estados Unidos. Al igual que Walter White, Gus era un criminal que se escondía \"en plena vista,\" recurriendo a su posición social como filántropo para ocultar su verdadera naturaleza según construía su imperio.\nWalter entró en contacto con Gus cuando buscaba un comprador para su metanfetamina de alto nivel de pureza química. Aunque Gus se mostró reacio a hacer negocios debido a sus observaciones de Jesse Pinkman como un drogadicto irresponsable, Walter logró convencerlo para que adquiriese la cantidad de producto que tenían. Viendo que el producto era bastante exitoso, Gus persuadió a Walter para que siguiese trabajando para él en su laboratorio. Aunque al principio ambos tenían una buena relación de negocios, varios sucesos acaban causando su deterioro, llegando al punto en que ambos eran adversarios. Por otra parte, su opinión sobre Jesse cambió favorablemente durante sus intentos de separarlo de Walter.','/api/files/da4a54d5-eefa-42ba-ae4a-61c5652f2ab4_Gus.jpeg','Gustavo Fring',' Co-fundador de Los Pollos Hermanos'),
(4,'2025-03-14 15:24:58.000000','Skyler White (de soltera Lambert) es la mujer de Walter White y madre de Walter White Jr. y Holly White. Skyler ha tenido múltiples trabajos o actividades para obtener dinero: escribiendo historias cortas, vendiendo objetos en eBay, trabajando como contable en Beneke Fabricators y ayudando a Walt con el local de lavado. Skyler quiere mucho a Walter, pero su matrimonio pasa a tener problemas debido a sus ausencias y su comportamiento extraño, lo cual acaba llevando a su separación.','/api/files/efa749c4-b539-4e05-8d69-dff6cbf8f0ab_Skyler.jpeg','Skyler White','Contable en Beneke Fabricators'),
(5,'2025-03-14 15:30:54.000000','Henry R. \"Hank\" Schrader es el marido de Marie Schrader (hermana de Skyler White) y agente especial a cargo de las oficinas de la DEA en Albuquerque. Un hombre enérgico y bullicioso, Hank es además cuñado de Walter White.\nA pesar de que es un agente extremadamente competente y que realmente se preocupa por Marie, Walter, Skyler y Walter Jr., su estilo a menudo acaba aislándole del peligro al que se expone diariamente.','/api/files/e5ff44c4-b11c-428d-b397-d2fb7788a91b_Hank.jpeg','Hank Schrader','Agente de la DEA'),
(6,'2025-03-14 15:32:14.000000','Hector \"Tío\" Salamanca fue uno de los hombres de confianza de Don Eladio en el Cartel Juárez. Como consecuencia de un ictus, acabó quedando inválido en una silla de ruedas sin poder hablar, teniendo que comunicarse a través de una campana acoplada a la silla. La DEA es consciente de su relación con el Cartel y de que es el tío de Tuco, pero asumen que ha estado fuera del negocio durante muchos años.','/api/files/5ae97777-dff5-4f52-9f25-234968730c3f_Hector.jpeg','Hector Salamanca','Ex-capo del Cártel de Juárez');
UNLOCK TABLES;